name: bible_pulse
description: Offline-first English and Amharic Bible reading and study app.
publish_to: 'none'
version: 1.1.0+5

environment:
  sdk: '>=3.6.0 <4.0.0'
  flutter: '>=3.27.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.1.1

  sqflite: ^2.3.0
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  path: ^1.9.1

  google_fonts: ^6.1.0

  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.17
  audio_session: ^0.1.18
  audio_service: ^0.18.18

  flutter_local_notifications: ^22.0.1
  timezone: ^0.11.1
  flutter_timezone: ^4.1.0

  screenshot: ^3.0.0
  image_gallery_saver_plus: ^5.1.1
  permission_handler: ^11.1.0

  intl: ^0.20.2
  uuid: ^4.2.2
  crypto: ^3.0.6

  http: ^1.1.0

  share_plus: ^7.2.1

  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  connectivity_plus: ^7.3.0

  flutter_animate: ^4.5.0
  home_widget: ^0.7.0
  image_picker: ^1.2.3
  image: ^4.9.1
  app_links: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ^2.3.6

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/content_manifest.json
    - assets/bible/web.json
    - assets/bible/kjv.json
    - assets/bible/asv.json
    - assets/bible/amh.json
    - assets/bible/weahadu_am-2000.json
    - assets/bible/weahadu_am-1980.json
    - assets/bible/weahadu_gez-1980.json
    - assets/bible/weahadu_gez-2014.json
    - assets/bible/weahadu_en-kjv.json
    - assets/bible/weahadu_am-nasv-2001.json
    - assets/bible/weahadu_am-1962.json
    - assets/bible/weahadu_ti-1997.json
    - assets/bible/weahadu_om-kitaaba.json
    - assets/bible/youversion_1787171339205_youversion_1392.json
    - assets/bible/youversion_1787176804618_youversion_1588.json
    - assets/bible/youversion_1787184289066_youversion_42.json
    - assets/bible/youversion_1787199377123_youversion_100.json
    - assets/bible/youversion_1787214512121_youversion_2692.json
    - assets/bible/youversion_1787226249615_youversion_130.json
    - assets/bible/youversion_1787253529049_youversion_4125.json
    - assets/catalog/bible_catalog.json
    - assets/catalog/audio_catalog.json
    - assets/catalog/web_henson_audio_manifest.json
    - assets/catalog/kjv_pdaudio_manifest.json
    - assets/catalog/amh_sermononline_manifest.json
    - assets/catalog/ti_sermononline_nt_manifest.json
    - assets/branding/bible_plus_logo.png
    - assets/bible/youversion_1787158115564_youversion_1260.json
    # large language packages are downloadable (not bundled)
