class BibleBookRef {
  final String usfm;
  final String name;
  final int chapterCount;
  final bool isOldTestament;

  const BibleBookRef(
    this.usfm,
    this.name,
    this.chapterCount,
    this.isOldTestament,
  );
}

const List<BibleBookRef> kProtestantCanon = [
  BibleBookRef('GEN', 'Genesis', 50, true),
  BibleBookRef('EXO', 'Exodus', 40, true),
  BibleBookRef('LEV', 'Leviticus', 27, true),
  BibleBookRef('NUM', 'Numbers', 36, true),
  BibleBookRef('DEU', 'Deuteronomy', 34, true),
  BibleBookRef('JOS', 'Joshua', 24, true),
  BibleBookRef('JDG', 'Judges', 21, true),
  BibleBookRef('RUT', 'Ruth', 4, true),
  BibleBookRef('1SA', '1 Samuel', 31, true),
  BibleBookRef('2SA', '2 Samuel', 24, true),
  BibleBookRef('1KI', '1 Kings', 22, true),
  BibleBookRef('2KI', '2 Kings', 25, true),
  BibleBookRef('1CH', '1 Chronicles', 29, true),
  BibleBookRef('2CH', '2 Chronicles', 36, true),
  BibleBookRef('EZR', 'Ezra', 10, true),
  BibleBookRef('NEH', 'Nehemiah', 13, true),
  BibleBookRef('EST', 'Esther', 10, true),
  BibleBookRef('JOB', 'Job', 42, true),
  BibleBookRef('PSA', 'Psalms', 150, true),
  BibleBookRef('PRO', 'Proverbs', 31, true),
  BibleBookRef('ECC', 'Ecclesiastes', 12, true),
  BibleBookRef('SNG', 'Song of Songs', 8, true),
  BibleBookRef('ISA', 'Isaiah', 66, true),
  BibleBookRef('JER', 'Jeremiah', 52, true),
  BibleBookRef('LAM', 'Lamentations', 5, true),
  BibleBookRef('EZK', 'Ezekiel', 48, true),
  BibleBookRef('DAN', 'Daniel', 12, true),
  BibleBookRef('HOS', 'Hosea', 14, true),
  BibleBookRef('JOL', 'Joel', 3, true),
  BibleBookRef('AMO', 'Amos', 9, true),
  BibleBookRef('OBA', 'Obadiah', 1, true),
  BibleBookRef('JON', 'Jonah', 4, true),
  BibleBookRef('MIC', 'Micah', 7, true),
  BibleBookRef('NAM', 'Nahum', 3, true),
  BibleBookRef('HAB', 'Habakkuk', 3, true),
  BibleBookRef('ZEP', 'Zephaniah', 3, true),
  BibleBookRef('HAG', 'Haggai', 2, true),
  BibleBookRef('ZEC', 'Zechariah', 14, true),
  BibleBookRef('MAL', 'Malachi', 4, true),
  BibleBookRef('MAT', 'Matthew', 28, false),
  BibleBookRef('MRK', 'Mark', 16, false),
  BibleBookRef('LUK', 'Luke', 24, false),
  BibleBookRef('JHN', 'John', 21, false),
  BibleBookRef('ACT', 'Acts', 28, false),
  BibleBookRef('ROM', 'Romans', 16, false),
  BibleBookRef('1CO', '1 Corinthians', 16, false),
  BibleBookRef('2CO', '2 Corinthians', 13, false),
  BibleBookRef('GAL', 'Galatians', 6, false),
  BibleBookRef('EPH', 'Ephesians', 6, false),
  BibleBookRef('PHP', 'Philippians', 4, false),
  BibleBookRef('COL', 'Colossians', 4, false),
  BibleBookRef('1TH', '1 Thessalonians', 5, false),
  BibleBookRef('2TH', '2 Thessalonians', 3, false),
  BibleBookRef('1TI', '1 Timothy', 6, false),
  BibleBookRef('2TI', '2 Timothy', 4, false),
  BibleBookRef('TIT', 'Titus', 3, false),
  BibleBookRef('PHM', 'Philemon', 1, false),
  BibleBookRef('HEB', 'Hebrews', 13, false),
  BibleBookRef('JAS', 'James', 5, false),
  BibleBookRef('1PE', '1 Peter', 5, false),
  BibleBookRef('2PE', '2 Peter', 3, false),
  BibleBookRef('1JN', '1 John', 5, false),
  BibleBookRef('2JN', '2 John', 1, false),
  BibleBookRef('3JN', '3 John', 1, false),
  BibleBookRef('JUD', 'Jude', 1, false),
  BibleBookRef('REV', 'Revelation', 22, false),
];

int get kTotalChapterCount =>
    kProtestantCanon.fold(0, (sum, book) => sum + book.chapterCount);
